import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

type JsonObject = Record<string, unknown>;

type GeneratedClass = {
  readonly type: string;
  readonly containerName: string | null;
  readonly isDeprecated: boolean;
  readonly propertyNames: readonly string[];
  readonly requiredProperties: readonly string[];
};

type GeneratedRelationshipType = {
  readonly relationshipType: string;
  readonly fromClassType: string;
  readonly toClassType: string;
  readonly dataGroupLabel: string;
};

function isJsonObject(value: unknown): value is JsonObject {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function readString(value: unknown, fallback: string): string {
  return typeof value === "string" ? value : fallback;
}

function readOptionalString(value: unknown): string | null {
  return typeof value === "string" && value.length > 0 ? value : null;
}

function readBoolean(value: unknown): boolean {
  return value === true;
}

function readStringArray(value: unknown): readonly string[] {
  return Array.isArray(value)
    ? value.filter((item): item is string => typeof item === "string")
    : [];
}

function extractClasses(lexicon: JsonObject): readonly GeneratedClass[] {
  const classes = Array.isArray(lexicon.classes) ? lexicon.classes : [];
  return classes.filter(isJsonObject).map((entry) => {
    const properties = isJsonObject(entry.properties) ? entry.properties : {};
    return {
      type: readString(entry.type, "unknown"),
      containerName: readOptionalString(entry.container_name),
      isDeprecated: readBoolean(entry.is_deprecated),
      propertyNames: Object.keys(properties).sort(),
      requiredProperties: readStringArray(entry.required).slice().sort(),
    };
  });
}

function extractRelationshipTypes(lexicon: JsonObject): readonly GeneratedRelationshipType[] {
  const dataGroups = Array.isArray(lexicon.data_groups) ? lexicon.data_groups : [];
  const relationships = new Map<string, GeneratedRelationshipType>();

  for (const dataGroup of dataGroups.filter(isJsonObject)) {
    const label = readString(dataGroup.label, "Unknown");
    const entries = Array.isArray(dataGroup.relationships)
      ? dataGroup.relationships
      : [];
    for (const relationship of entries.filter(isJsonObject)) {
      const relationshipType = readString(relationship.relationship_type, "");
      const fromClassType = readString(relationship.from, "");
      const toClassType = readString(relationship.to, "");
      if (!relationshipType || !fromClassType || !toClassType) continue;
      const key = `${relationshipType}|${fromClassType}|${toClassType}`;
      if (!relationships.has(key)) {
        relationships.set(key, {
          relationshipType,
          fromClassType,
          toClassType,
          dataGroupLabel: label,
        });
      }
    }
  }

  return Array.from(relationships.values()).sort((left, right) =>
    left.relationshipType.localeCompare(right.relationshipType) ||
    left.fromClassType.localeCompare(right.fromClassType) ||
    left.toClassType.localeCompare(right.toClassType),
  );
}

function renderGeneratedFile(params: {
  readonly classes: readonly GeneratedClass[];
  readonly relationshipTypes: readonly GeneratedRelationshipType[];
}): string {
  const classJson = JSON.stringify(params.classes, null, 2);
  const relationshipJson = JSON.stringify(params.relationshipTypes, null, 2);
  return `// Generated by scripts/generate-lexicon-metadata.ts. Do not edit by hand.\n\nexport const lexiconClasses = ${classJson} as const;\n\nexport const lexiconRelationshipTypes = ${relationshipJson} as const;\n\nexport const lexiconClassTypes = lexiconClasses.map((entry) => entry.type);\n\nexport const lexiconRelationshipTypeNames = lexiconRelationshipTypes.map((entry) => entry.relationshipType);\n\nexport type LexiconClassType = (typeof lexiconClasses)[number]["type"];\n\nexport type LexiconRelationshipType = (typeof lexiconRelationshipTypes)[number]["relationshipType"];\n`;
}

async function main(): Promise<void> {
  const lexiconPath = path.resolve("../lexicon/src/data/lexicon.json");
  const outputPath = path.resolve("src/lexicon/generated.ts");
  const raw = await readFile(lexiconPath, "utf8");
  const parsed: unknown = JSON.parse(raw);
  if (!isJsonObject(parsed)) {
    throw new Error(`Expected lexicon JSON object at ${lexiconPath}`);
  }
  const classes = extractClasses(parsed);
  const relationshipTypes = extractRelationshipTypes(parsed);
  await mkdir(path.dirname(outputPath), { recursive: true });
  await writeFile(outputPath, renderGeneratedFile({ classes, relationshipTypes }));
}

await main();
